"""Added Bus model

Revision ID: 010f816ddb26
Revises: d9f1769c351d
Create Date: 2026-07-20 00:55:31.907104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010f816ddb26'
down_revision = 'd9f1769c351d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('bus_name', sa.String(length=100), nullable=False),
    sa.Column('bus_number', sa.String(length=30), nullable=False),
    sa.Column('bus_type', sa.String(length=30), nullable=True),
    sa.Column('total_seats', sa.Integer(), nullable=True),
    sa.Column('amenities', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bus_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buses')
    # ### end Alembic commands ###
