"""Updated Trip model

Revision ID: 01defa6ca6f7
Revises: 6d87a7143e31
Create Date: 2026-07-20 20:06:07.685500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01defa6ca6f7'
down_revision = '6d87a7143e31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('boarding_point', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('dropping_point', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('total_seats', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('total_seats')
        batch_op.drop_column('dropping_point')
        batch_op.drop_column('boarding_point')

    # ### end Alembic commands ###
