"""Added Trip model

Revision ID: 03acde0f51a1
Revises: 010f816ddb26
Create Date: 2026-07-20 17:45:21.181445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03acde0f51a1'
down_revision = '010f816ddb26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('from_city', sa.String(length=100), nullable=False),
    sa.Column('to_city', sa.String(length=100), nullable=False),
    sa.Column('journey_date', sa.Date(), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=False),
    sa.Column('fare', sa.Integer(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips')
    # ### end Alembic commands ###
