"""Updated Bus model

Revision ID: 6d87a7143e31
Revises: 03acde0f51a1
Create Date: 2026-07-20 20:03:27.995959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d87a7143e31'
down_revision = '03acde0f51a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('front_photo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('back_photo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('left_photo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('right_photo', sa.String(length=255), nullable=True))

    with op.batch_alter_table('operators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.drop_constraint(batch_op.f('operators_email_key'), type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('operators_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('status')

    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.drop_column('right_photo')
        batch_op.drop_column('left_photo')
        batch_op.drop_column('back_photo')
        batch_op.drop_column('front_photo')
        batch_op.drop_column('registration_number')

    # ### end Alembic commands ###
