"""Updated bus photo field

Revision ID: c780dcc4f028
Revises: 7c370403b93e
Create Date: 2026-07-21 13:33:50.944148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c780dcc4f028'
down_revision = '7c370403b93e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bus_photo', sa.String(length=255), nullable=True))
        batch_op.drop_column('back_photo')
        batch_op.drop_column('left_photo')
        batch_op.drop_column('right_photo')
        batch_op.drop_column('front_photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('front_photo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('right_photo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('left_photo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('back_photo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('bus_photo')

    # ### end Alembic commands ###
